CREATE TABLE BRANDS (
    BRAND_ID BIGINT PRIMARY KEY AUTOINCREMENT,
    BRAND_NAME VARCHAR(164),
    EMAIL VARCHAR(200) UNIQUE,
    ADDRESS VARCHAR(64),
    CITY VARCHAR(65),
    COUNTRY VARCHAR(12)
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR(32) PRIMARY KEY,
    NAME VARCHAR(200),
    SIZE INT,
    VARIETY VARCHAR(30),
    PRICE NUMERIC (4,2)
    STATUS VARCHAR(16)
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID BIGINT PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME VARCHAR(64),
    LAST_NAME VARCHAR(64),
    EMAIL VARCHAR(200) UNIQUE,
    ADDRESS VARCHAR(64),
    CITY VARCHAR(65),
    POSTCODE VARCHAR(12)
);

CREATE TABLE ORDERS (
    ID VARCHAR(16) PRIMARY KEY,
    CUSTOMER_ID BIGINT,
    BRAND_ID BIGINT
);

CREATE TABLE ORDER_LINES (
    ORDER_LINE_ID BIGINT PRIMARY KEY AUTOINCREMENT,
    ORDER_ID VARCHAR(16),
    PRODUCT_ID VARCHAR(32),
    QUANTITY INT
);

ALTER TABLE ORDERS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID);
ALTER TABLE ORDERS ADD FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(BRAND_ID);
ALTER TABLE ORDERS_LINES ADD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);
ALTER TABLE ORDERS_LINES ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID);
